### ISSUE TITLE
启动app.py后无法访问网页

### ISSUE THREAD

**Issue by 6qs2w9oxhina** [GamerNoTitle/CraftMon#4]
系统版本 : windows 10 21h2
python 版本 : 3.10.2
用python -m pip install -r "requirements.txt" 安装完依赖后，使用python app.py 启动，用浏览器访问，提示 500 Internat Server Error。
命令行显示出来如下错误。
[error.log](https://github.com/user-attachments/files/20537524/error.log)

**Comment by GamerNoTitle** [comment]
你的这个网页连不上你的服务器

**Comment by 6qs2w9oxhina** [comment]
这个就是用刚解压出来的文件，就是改了个端口号，其他的都没改过。

**Comment by GamerNoTitle** [comment]
那当然连不上啊，我服务器没开在 `mc.bili33.top:25565` 啊……
你改成你自己的连接信息呗
```yaml
  # 服务器地址
  host: mc.bili33.top
  # 既是获取信息的端口，也是用来展示的端口
  port: 25565
```
